Verificando o conteúdo do dataset:

In [1]:
from google.colab import drive 
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta

drive.mount('/content/gdrive')

caminho='gdrive/MyDrive/ufsm/aulas/introducao_ciencia_analise_dados_2022_1/aulas_13_16_python/'
#caminho='./'

nome='dataset_bancomundial.csv'

nomecaminho=caminho+nome

# le o dataset cujo nome esta definido na variavel 'nomecaminho'
gfdd = pd.read_csv(nomecaminho, sep=';', decimal=',')

gfdd

Mounted at /content/gdrive

,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,0,Afghanistan,AFG,5-bank asset concentration,GFDD.OI.06,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,100.0,100.0,94.392921,89.846954,90.01989,87.100861,85.567154,89.463562
1,1,Afghanistan,AFG,Account at a formal financial institution (% a...,GFDD.AI.05,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.005013,NaN,NaN
2,2,Afghanistan,AFG,Account used for business purposes (% age 15+),GFDD.AI.08,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.718403,NaN,NaN
3,3,Afghanistan,AFG,Account used to receive government payments (%...,GFDD.AI.09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.991833,NaN,NaN
4,4,Afghanistan,AFG,Account used to receive remittances (% age 15+),GFDD.AI.10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.727025,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24950,24950,Zimbabwe,ZWE,Syndicated loan issuance volume to GDP (%),GFDD.DM.12,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24951,24951,Zimbabwe,ZWE,Total factoring volume to GDP (%),GFDD.OI.18,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24952,24952,Zimbabwe,ZWE,Value of collateral needed for a loan (% of th...,GFDD.AI.31,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,261.300000,NaN,NaN
24953,24953,Zimbabwe,ZWE,Value traded excluding top 10 traded companies...,GFDD.AM.01,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24954,24954,Zimbabwe,ZWE,Working capital financed by banks (%),GFDD.AI.35,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.500000,NaN,NaN

In [ ]:
Verificando o conteúdo do cabeçalho por um número determinado de linhas:

In [ ]:
from google.colab import drive 
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta

drive.mount('/content/gdrive')

caminho='gdrive/MyDrive/ufsm/aulas/introducao_ciencia_analise_dados_2022_1/aulas_13_16_python/'
#caminho='./'

nome='dataset_bancomundial.csv'

nomecaminho=caminho+nome

# le o dataset cujo nome esta definido na variavel 'nomecaminho'
gfdd = pd.read_csv(nomecaminho, sep=';', decimal=',')

gfdd.head(5)

,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,0,Afghanistan,AFG,5-bank asset concentration,GFDD.OI.06,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,100.0,100.0,94.392921,89.846954,90.01989,87.100861,85.567154,89.463562
1,1,Afghanistan,AFG,Account at a formal financial institution (% a...,GFDD.AI.05,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.005013,NaN,NaN
2,2,Afghanistan,AFG,Account used for business purposes (% age 15+),GFDD.AI.08,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.718403,NaN,NaN
3,3,Afghanistan,AFG,Account used to receive government payments (%...,GFDD.AI.09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.991833,NaN,NaN
4,4,Afghanistan,AFG,Account used to receive remittances (% age 15+),GFDD.AI.10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.727025,NaN,NaN

In [ ]:
Preenchendo campos "NaN" em "-1" no dataframe:

In [ ]:
from google.colab import drive 
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta

drive.mount('/content/gdrive')

caminho='gdrive/MyDrive/ufsm/aulas/introducao_ciencia_analise_dados_2022_1/aulas_13_16_python/'
#caminho='./'

nome='dataset_bancomundial.csv'

nomecaminho=caminho+nome

# le o dataset cujo nome esta definido na variavel 'nomecaminho'
gfdd = pd.read_csv(nomecaminho, sep=';', decimal=',')

gfdd.fillna(-1, inplace=True)

gfdd

,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,0,Afghanistan,AFG,5-bank asset concentration,GFDD.OI.06,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,100.0,100.0,94.392921,89.846954,90.01989,87.100861,85.567154,89.463562
1,1,Afghanistan,AFG,Account at a formal financial institution (% a...,GFDD.AI.05,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,9.005013,-1.000000,-1.000000
2,2,Afghanistan,AFG,Account used for business purposes (% age 15+),GFDD.AI.08,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,2.718403,-1.000000,-1.000000
3,3,Afghanistan,AFG,Account used to receive government payments (%...,GFDD.AI.09,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,1.991833,-1.000000,-1.000000
4,4,Afghanistan,AFG,Account used to receive remittances (% age 15+),GFDD.AI.10,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,1.727025,-1.000000,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24950,24950,Zimbabwe,ZWE,Syndicated loan issuance volume to GDP (%),GFDD.DM.12,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000
24951,24951,Zimbabwe,ZWE,Total factoring volume to GDP (%),GFDD.OI.18,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000
24952,24952,Zimbabwe,ZWE,Value of collateral needed for a loan (% of th...,GFDD.AI.31,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,261.300000,-1.000000,-1.000000
24953,24953,Zimbabwe,ZWE,Value traded excluding top 10 traded companies...,GFDD.AM.01,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,-1.000000,-1.000000,-1.000000
24954,24954,Zimbabwe,ZWE,Working capital financed by banks (%),GFDD.AI.35,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.000000,-1.000000,-1.00000,5.500000,-1.000000,-1.000000

In [ ]:
Verificando as colunas do dataset:

In [2]:
from google.colab import drive 
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta

drive.mount('/content/gdrive')

caminho='gdrive/MyDrive/ufsm/aulas/introducao_ciencia_analise_dados_2022_1/aulas_13_16_python/'
#caminho='./'

nome='dataset_bancomundial.csv'

nomecaminho=caminho+nome

# le o dataset cujo nome esta definido na variavel 'nomecaminho'
gfdd = pd.read_csv(nomecaminho, sep=';', decimal=',')

gfdd.columns

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

Index(['index', 'Country Name', 'Country Code', 'Indicator Name',
       'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013'],
      dtype='object')

In [ ]:
Verificando os valores únicos da coluna 'Indicator Name':

In [3]:
from google.colab import drive 
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta

drive.mount('/content/gdrive')

caminho='gdrive/MyDrive/ufsm/aulas/introducao_ciencia_analise_dados_2022_1/aulas_13_16_python/'
#caminho='./'

nome='dataset_bancomundial.csv'

nomecaminho=caminho+nome

# le o dataset cujo nome esta definido na variavel 'nomecaminho'
gfdd = pd.read_csv(nomecaminho, sep=';', decimal=',')

num_valores_distintos = gfdd['Indicator Name'].nunique()

print(num_valores_distintos)

gfdd['Indicator Name'].unique()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
115

array(['5-bank asset concentration',
       'Account at a formal financial institution (% age 15+)',
       'Account used for business purposes (% age 15+)',
       'Account used to receive government payments (% age 15+)',
       'Account used to receive remittances (% age 15+)',
       'Account used to receive wages (% age 15+)',
       'ATMs per 100,000 adults', 'Bank accounts per 1,000 adults',
       'Bank branches per 100,000 adults',
       'Bank capital to total assets (%)', 'Bank concentration (%)',
       'Bank cost to income ratio (%)',
       'Bank credit to bank deposits (%)', 'Bank deposits to GDP (%)',
       'Bank lending-deposit spread', 'Bank net interest margin (%)',
       'Bank noninterest income to total income (%)',
       'Bank nonperforming loans to gross loans (%)',
       'Bank overhead costs to total assets (%)',
       'Bank regulatory capital to risk-weighted assets (%)',
       'Bank return on assets (%, after tax)',
       'Bank return on assets (%, before tax)',
       'Bank return on equity (%, after tax)',
       'Bank return on equity (%, before tax)', 'Bank Z-score',
       'Banking crisis dummy (1=banking crisis, 0=none)',
       'Boone indicator', 'Central bank assets to GDP (%)',
       'Checks used to make payments (% age 15+)',
       'Consolidated foreign claims of BIS reporting banks to GDP (%)',
       'Consumer price index (2005=100, average)',
       'Consumer price index (2005=100, December)',
       'Corporate bond average maturity (years)',
       'Corporate bond issuance volume to GDP (%)',
       'Credit card (% age 15+)',
       'Credit to government and state owned enterprises to GDP (%)',
       'Debit card (% age 15+)',
       'Deposit money bank assets to deposit money bank assets and central bank assets (%)',
       "Deposit money banks' assets to GDP (%)",
       'Depositing/withdrawing at least once in a typical month (% age 15+)',
       'Domestic credit to private sector (% of GDP)',
       'Electronic payments used to make payments (% age 15+)',
       'External loans and deposits of reporting banks vis-√†-vis all sectors (% of domestic bank deposits)',
       'External loans and deposits of reporting banks vis-√†-vis the banking sector (% of domestic bank deposits)',
       'External loans and deposits of reporting banks vis-√†-vis the nonbanking sectors (% of domestic bank deposits)',
       'Financial system deposits to GDP (%)',
       'Firms identifying access to finance as a major constraint (%)',
       'Firms not needing a loan (%)',
       'Firms using banks to finance investments (%)',
       'Firms using banks to finance working capital (%)',
       'Firms whose recent loan application was rejected (%)',
       'Firms with a bank loan or line of credit (%)',
       'Firms with a checking or savings account (%)',
       'Foreign bank assets among total bank assets (%)',
       'Foreign banks among total banks (%)', 'GDP (Current USD)',
       'GDP per capita (Constant 2005 USD)',
       'Global leasing volume to GDP (%)', 'GNI (Current USD)',
       'Gross portfolio debt assets to GDP (%)',
       'Gross portfolio debt liabilities to GDP (%)',
       'Gross portfolio equity assets to GDP (%)',
       'Gross portfolio equity liabilities to GDP (%)', 'H-statistic',
       'Insurance company assets to GDP (%)',
       'International debt issues to GDP (%)',
       'Investments financed by banks (%)',
       'Investments financed by equity or stock sales (%)',
       'Lerner index', 'Life insurance premium volume to GDP (%)',
       'Liquid assets to deposits and short term funding (%)',
       'Liquid liabilities in millions USD (2000 constant)',
       'Liquid liabilities to GDP (%)',
       'Loan from a financial institution in the past year (% age 15+)',
       'Loan from a private lender in the past year (% age 15+)',
       'Loan from an employer in the past year (% age 15+)',
       'Loan from family or friends in the past year (% age 15+)',
       'Loan in the past year (% age 15+)',
       'Loan through store credit in the past year (% age 15+)',
       'Loans from nonresident banks (amounts outstanding) to GDP (%)',
       'Loans from nonresident banks (net) to GDP (%)',
       'Loans requiring collateral (%)',
       'Market capitalization excluding top 10 companies to total market capitalization (%)',
       'Mobile phone used to pay bills (% age 15+)',
       'Mobile phone used to send money (% age 15+)',
       'Mutual fund assets to GDP (%)',
       'Nonbank financial institutions‚Äô assets to GDP (%)',
       'Nonfinancial corporate bonds to total bonds and notes outstanding (%)',
       'Nonlife insurance premium volume to GDP (%)',
       'Number of listed companies per 1,000,000 people',
       'Outstanding domestic private debt securities to GDP (%)',
       'Outstanding domestic public debt securities to GDP (%)',
       'Outstanding international private debt securities to GDP (%)',
       'Outstanding international public debt securities to GDP (%)',
       'Pension fund assets to GDP (%)', 'Population (Total)',
       'Private credit by deposit money banks and other financial institutions to GDP (%)',
       'Private credit by deposit money banks to GDP (%)',
       'Provisions to nonperforming loans (%)',
       'Remittance inflows to GDP (%)',
       'Saved any money in the past year (% age 15+)',
       'Saved at a financial institution in the past year (% age 15+)',
       'Saved using a savings club in the past year (% age 15+)',
       'Small firms with a bank loan or line of credit (%)',
       'Stock market capitalization to GDP (%)',
       'Stock market return (%, year-on-year)',
       'Stock market total value traded to GDP (%)',
       'Stock market turnover ratio (%)', 'Stock price volatility',
       'Syndicated loan average maturity (years)',
       'Syndicated loan issuance volume to GDP (%)',
       'Total factoring volume to GDP (%)',
       'Value of collateral needed for a loan (% of the loan amount)',
       'Value traded excluding top 10 traded companies to total value traded (%)',
       'Working capital financed by banks (%)'], dtype=object)

In [ ]:
Buscando as linhas cujas coluna 'Indicator Name' que contenha 'GDP per capita':

In [8]:
from google.colab import drive 
import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta

drive.mount('/content/gdrive')

caminho='gdrive/MyDrive/ufsm/aulas/introducao_ciencia_analise_dados_2022_1/aulas_13_16_python/'
#caminho='./'

nome='dataset_bancomundial.csv'

nomecaminho=caminho+nome

# le o dataset cujo nome esta definido na variavel 'nomecaminho'
gfdd = pd.read_csv(nomecaminho, sep=';', decimal=',')

conteudo_coluna='GDP per capita'

gfdd_linhas_gdp = gfdd[ gfdd['Indicator Name'].str.contains(conteudo_coluna) ]
gfdd_linhas_gdp = gfdd_linhas_gdp.reset_index(drop=True)

linhas,colunas=gfdd_linhas_gdp.shape
print('Número de linhas : ',linhas)
print('Número de colunas : ',colunas)


#print('Número de linhas : ', gfdd_linhas_gdp.shape[0])

gfdd_linhas_gdp.head(10)

#print(len(gfdd_linhas_gdp))

#gfdd.columns

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Número de linhas :  217
Número de colunas :  59

,index,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,56,Afghanistan,AFG,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,234.996625,252.407893,258.418692,285.917091,288.758200,340.931427,360.705615,373.451677,417.055042,415.003478
1,171,Albania,ALB,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,2623.046356,2781.510727,2939.071105,3136.090047,3398.412855,3536.153569,3685.487144,3790.018085,3857.254570,3916.144766
2,286,Algeria,DZA,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,1765.594712,1488.051250,1166.444702,1529.072727,1578.458614,...,2912.290298,3038.748713,3041.480757,3092.039129,3098.409819,3091.058258,3143.629137,3171.735083,3215.206987,3243.990093
3,401,Andorra,ADO,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,30329.589910,31268.966740,33125.386790,33840.224790,35628.410700,NaN,NaN,NaN,NaN,NaN
4,516,Angola,AGO,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,1494.297297,1706.543621,1990.840900,2359.279962,2597.055971,2573.687194,2576.646856,2593.843498,2643.720551,2737.877052
5,631,Antigua and Barbuda,ATG,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,11505.185530,12079.865480,13547.711590,14671.133550,14517.805180,12629.713560,11602.142020,11275.279960,11607.745140,11481.384990
6,746,Argentina,ARG,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,3732.330981,3871.977071,3778.406097,3522.337065,3820.330238,...,5328.560130,5767.657012,6195.384942,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,861,Armenia,ARM,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,1422.403624,1625.396904,1847.273054,2110.415004,2265.424536,1950.983276,1997.038912,2090.459569,2237.228245,2309.708500
8,976,Aruba,ABW,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,NaN,NaN,NaN,NaN,NaN,...,23517.573610,23302.831990,23662.635650,22710.239140,21121.395200,19912.756660,NaN,NaN,NaN,NaN
9,1091,Australia,AUS,GDP per capita (Constant 2005 USD),NY.GDP.PCAP.KD,13510.590260,13555.788070,13397.885380,13959.911740,14643.588070,...,33374.034300,33995.851670,34499.830820,35574.154560,36159.264740,36035.071730,36175.030410,36504.173940,37218.081690,37491.506680